language: python
sudo: false
python:
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
